# Generated by Django 3.2 on 2021-04-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_price_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'گروه', 'verbose_name_plural': '۱.گروه ها'},
        ),
        migrations.AlterModelOptions(
            name='imagealbum',
            options={'verbose_name': 'آلبوم', 'verbose_name_plural': '۳.آلبوم ها'},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'عکس', 'verbose_name_plural': '۴.عکس ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'محصول', 'verbose_name_plural': '۲.محصولات'},
        ),
    ]
