# Generated by Django 3.2 on 2021-04-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210428_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagealbum',
            options={'verbose_name': 'آلبوم', 'verbose_name_plural': '۴.آلبوم ها'},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'عکس', 'verbose_name_plural': '۳.عکس ها'},
        ),
    ]
