# Generated by Django 3.2 on 2021-04-28 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210428_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagealbum',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='shop.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='بروز رسانی محصول'),
        ),
    ]
