# Generated by Django 3.2 on 2021-04-28 22:51

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.IntegerField(default=shop.models.random_int, editable=False, verbose_name='کد محصول'),
        ),
    ]
