# Generated by Django 3.2 on 2021-05-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'جزئیات سفارش', 'verbose_name_plural': 'جزئیات سفارش'},
        ),
    ]
