# Generated by Django 3.2 on 2021-05-05 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='percent',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
