# Generated by Django 3.2 on 2021-05-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210505_1222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
